- hosts: all
  become: yes
  roles:
    - common
    - containerd
    - kubernetes

- hosts: masters
  become: yes
  roles:
    - master-init

- hosts: workers
  become: yes
  roles:
    - worker-join
